# Generated by Django 4.2.23 on 2025-07-02 21:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                ("run_id", models.AutoField(primary_key=True, serialize=False)),
                ("run_number", models.IntegerField(unique=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("run_conditions", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "runs",
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("subscriber_id", models.AutoField(primary_key=True, serialize=False)),
                ("subscriber_name", models.CharField(max_length=255, unique=True)),
                ("fraction", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "subscribers",
            },
        ),
        migrations.CreateModel(
            name="StfFile",
            fields=[
                (
                    "file_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("machine_state", models.CharField(default="physics", max_length=64)),
                ("file_url", models.URLField(max_length=1024, unique=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=64, null=True)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("sent_to_mq", "Sent to MQ"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stf_files",
                        to="database.run",
                    ),
                ),
            ],
            options={
                "db_table": "stf_files",
            },
        ),
        migrations.CreateModel(
            name="MessageQueueDispatch",
            fields=[
                (
                    "dispatch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dispatch_time", models.DateTimeField(auto_now_add=True)),
                ("message_content", models.JSONField(blank=True, null=True)),
                ("is_successful", models.BooleanField()),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "stf_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="database.stffile",
                    ),
                ),
            ],
            options={
                "db_table": "message_queue_dispatches",
            },
        ),
    ]
