# Generated by Django 4.2 on 2025-07-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stffile",
            name="status",
            field=models.CharField(
                choices=[
                    ("registered", "Registered"),
                    ("processing", "Processing"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                    ("done", "Done"),
                ],
                default="registered",
                max_length=20,
            ),
        ),
    ]
