# Generated by Django 4.2 on 2025-07-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_alter_stffile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagequeuedispatch",
            name="is_successful",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
