name: FastMon Utils Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run fastmon_utils tests
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: '1'  # avoid loading external pytest plugins
        run: |
          pytest -vs -q src/swf_fastmon_agent/tests/test_fastmon_utils.py

